# Generated by Django 2.0.4 on 2018-07-04 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointee',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
