# Generated by Django 2.0.4 on 2018-07-04 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0002_appointee_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointee',
            name='appointment',
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='appointee', to='office.Appointee'),
        ),
    ]
