# Generated by Django 2.0.4 on 2018-07-04 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0003_auto_20180704_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointee',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='appointee',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
