# Generated by Django 2.0.4 on 2018-07-09 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0004_auto_20180704_2332'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ('-start_time',)},
        ),
        migrations.AlterField(
            model_name='appointee',
            name='photo',
            field=models.ImageField(blank=True, upload_to='profile/images'),
        ),
    ]
