# Generated by Django 2.0.4 on 2018-07-09 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0005_auto_20180709_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointee',
            name='photo',
            field=models.ImageField(blank=True, upload_to='office/images'),
        ),
    ]
